version: '3.8'


services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - appointment-service
      - user-service

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - healthcare_network

  authentication-service:
    build: 
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/healthcare
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRATION=24h
      - PORT=8000
    depends_on:
      - mongodb
    networks:
      - healthcare_network
    restart: unless-stopped

  appointment-service:
    build: 
      context: ./appointment-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/healthcare
    depends_on:
      - mongodb
      - authentication-service
    networks:
      - healthcare_network
    restart: unless-stopped

  transaction-service:
    build: 
      context: ./transiaction-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/healthcare
    depends_on:
      - mongodb
      - authentication-service
    networks:
      - healthcare_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_APPOINTMENT_API_URL=http://localhost:3000
      - REACT_APP_TRANSACTION_API_URL=http://localhost:3002
    depends_on:
      - authentication-service
      - appointment-service
      - transaction-service
    networks:
      - healthcare_network
    restart: unless-stopped

networks:
  healthcare_network:
    driver: bridge

volumes:
  mongodb_data:
