version: '3.8'

services:
  api-gateway:
    image: your-dockerhub-username/api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://authentication-service:8000
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8081
      - TRANSACTION_SERVICE_URL=http://transaction-service:8082
      - FRONTEND_URL=http://frontend:3000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - authentication-service
      - appointment-service
      - transaction-service
      - frontend

  authentication-service:
    image: your-dockerhub-username/authentication-service:latest
    container_name: authentication-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=${MONGO_URI}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  appointment-service:
    image: your-dockerhub-username/appointment-service:latest
    container_name: appointment-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - authentication-service

  transaction-service:
    image: your-dockerhub-username/transaction-service:latest
    container_name: transaction-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - authentication-service
      - appointment-service

  frontend:
    image: your-dockerhub-username/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - authentication-service
      - appointment-service
      - transaction-service

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
