version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://authentication-service:8000
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8081
      - TRANSACTION_SERVICE_URL=http://transaction-service:8082
      - FRONTEND_URL=http://frontend:3000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - authentication-service
      - appointment-service
      - transaction-service
      - frontend

  authentication-service:
    build: ./authentication-service-node
    container_name: authentication-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=${MONGO_URI}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  appointment-service:
    build: ./appointment-service-node
    container_name: appointment-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - authentication-service

  transaction-service:
    build: ./transaction-service-node
    container_name: transaction-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - authentication-service
      - appointment-service

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - authentication-service
      - appointment-service
      - transaction-service

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
