version: '3.8'
services:
  appointment-service:
    build: ./appointment-service
    ports:
      - "3000:3000"
    restart: unless-stopped

  authentication-service:
    build: ./authentication-service
    ports:
      - "3001:3001"
    restart: unless-stopped

  transiaction-service:
    build: ./transiaction-service
    ports:
      - "3002:3002"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - appointment-service
      - authentication-service
      - transiaction-service
    restart: unless-stopped
